### ISSUE TITLE
Error building project after adding pod

### ISSUE THREAD

**Issue by ericgross** [netguru/carrierwave-ios#1]
I have added this pod and now when building I get the error:

Users/user1/Documents/demo1/Pods/Carrierwave/Carrierwave/CRVImageEditGlassView.m:98:26: error: implicit declaration of function 'CRVWorkInProgress' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
- (void)layoutSubviews { CRVWorkInProgress("Layout mechanism has to be improved");

**Comment by PatrykKaczmarek** [comment]
Hello @ericgross 

Framework is still under development. As you see, some flags (like `CRVWorkInProgress`) don't allow to build pod. It prevents also for usage it before carrierwave-ios will be fully completed and ready to deliver.

Please stay tuned. We will release stable version soon.

**Comment by PatrykKaczmarek** [comment]
Hi @ericgross 

We are happy to announce that carrierwave - iOS is ready for use. Also do not forget to check [our ruby gem](https://github.com/carrierwaveuploader/carrierwave) which simplifies communication with native carrierwave. You can also read our blog post: [Carrierwave-iOS in Open Source: Easier File Networking](https://netguru.co/blog/carrierwave-ios-in-open-source)
