### ISSUE TITLE
Feature Request: CRVImageEditViewController Crop fixed ratio

### ISSUE THREAD

**Issue by tdroenner** [netguru/carrierwave-ios#2]
I would like to have the possibility to have a crop rectangle with a fixed aspect ratio. The user should only be able to pull at the corners.

**Comment by PatrykKaczmarek** [comment]
Hey @tdroenner 

`CropView` has already implemented such feature. Here is the [flag](https://github.com/netguru/carrierwave-ios/blob/master/Carrierwave/CRVScalableView.h#L56) indicating whether should keep ratio or not. If `cropView` should animate to given ratio please use:
```
- (void)animateToRatio:(CGFloat)ratio completion:(void (^)(BOOL finished))completion;
```
method and in completion block set flag `ratioEnabled` to `YES`. 

`CRVImageEditViewController` uses this mechanism [here](https://github.com/netguru/carrierwave-ios/blob/master/Carrierwave/CRVImageEditViewController.m#L113).

If you want to draw border, anchors, grid by yourself please set:
- `CRVGridDrawingMode` to `CRVGridDrawingModeNever`
- `CRVBorderDrawingMode` to `CRVBorderDrawingModeNever`
- `CRVAnchorsDrawingMode` to `CRVAnchorsDrawingModeNever`

and confirm `CRVScalableBorderDelegate` within you can draw customise drawings:
```
- (void)drawRect:(CGRect)rect withinContext:(CGContextRef)context;
```
**Notice** to draw always in prepared context.

Does it solve your request?

**Comment by PatrykKaczmarek** [comment]
Hi @tdroenner any update? 

I will close issue but feel free to reopen if there will be any ambiguity.
