### ISSUE TITLE
Unable to get example carrier wave ios application working

### ISSUE THREAD

**Issue by rememberlenny** [netguru/carrierwave-ios#3]
Can you add some basic instructions on getting the Carrierwave Demo to work?

Im getting Module 'Carrierwave' not found.

**Comment by PatrykKaczmarek** [comment]
Hi @rememberlenny 

To install carrierwave correctly, please follow [readme](https://github.com/netguru/carrierwave-ios#demo) instructions:
```
$ git clone --recursive git@github.com:netguru/carrierwave-ios.git
$ carthage update
$ pod install
```

**Comment by PatrykKaczmarek** [comment]
I'm assuming that you have installed carrierwave successfully. Please let me know if something went wrong.
