### ISSUE TITLE
NGRCrop repo not found

### ISSUE THREAD

**Issue by JakeSc** [netguru/carrierwave-ios#4]
I'm trying to run the demo, and Cocoapods can't find the netguru/ngrcrop-ios repository. Is it public?

```
[!] Error installing NGRCrop
[!] /usr/bin/git clone git@github.com:netguru/ngrcrop-ios.git

Cloning into '/var/folders/...'

ERROR: Repository not found.
fatal: Could not read from remote repository.


Please make sure you have the correct access rights and the repository exists.
```

**Comment by PatrykKaczmarek** [comment]
When using cocapods please specify tag in your Podfile:
```
pod 'Carrierwave', '~> 0.1.0'
```

Carrierwave is under enhancement right now and contains dependency which isn't public (as you said).
